### ISSUE TITLE
run_angle.py - angle values on the picture

### ISSUE THREAD

**Issue by MadisLemsalu** [raspberry-pi-maker/NVIDIA-Jetson#1]
parts = [part for idx, part in humans[0].body_parts.items()]
    for part in parts:
        print(part.get_part_name())
        print('No:%d X:%d Y:%d Score:%f'%( part.part_idx, int(part.x * image_w + 0.5), int(part.y * image_h + 0.5), part.score))
        cv2.putText(image,str(**???**),(int(part.x * image_w + 0.5), int(part.y * image_h + 0.5)), font, 1, (0,255,0), 2)

How would it be possible to print the found angle values on the heatmap, and not the value of the bodypart itself. **???** part of the code is where the code should be changed, but I don't know what should go in there.

**Comment by raspberry-pi-maker** [comment]
I didn't test the heatmap.
But I think,  if you want to insert the angle informations  to the heatmap, you might modify the original framework source codes at https://github.com/ildoonet/tf-pose-estimation.

**Comment by MadisLemsalu** [comment]
I figured it out:
  cv2.putText(image,str(round(angle_right_knee(humans[0]),2)),(int(542), int(385)), font, 1, (0,255,0), 2)
